apiVersion: v1
kind: ServiceAccount
metadata:
  name: planning-poker-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "planning-poker.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: planning-poker-web
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "planning-poker.labels" . | nindent 4 }}
automountServiceAccountToken: false
