apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.nameOverride | default (include "homechef-web.fullname" .) }}
  labels:
    {{- include "homechef-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "homechef-web.selectorLabels" . | nindent 4 }}
    homechef.tesserix.io/stack: deployment
