apiVersion: v1
kind: ServiceAccount
metadata:
  name: fe3dr-secret-reader
  namespace: tesserix
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: openbao-fe3dr-shared
  namespace: tesserix
spec:
  provider:
    vault:
      server: http://openbao.openbao.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: read-fe3dr-tesserix
          serviceAccountRef:
            name: fe3dr-secret-reader
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fe3dr-secret-reader
  namespace: roamie
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: openbao-fe3dr-shared
  namespace: roamie
spec:
  provider:
    vault:
      server: http://openbao.openbao.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: read-fe3dr-roamie
          serviceAccountRef:
            name: fe3dr-secret-reader
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fe3dr-secret-reader
  namespace: support-platform
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: openbao-fe3dr-shared
  namespace: support-platform
spec:
  provider:
    vault:
      server: http://openbao.openbao.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: read-fe3dr-support-platform
          serviceAccountRef:
            name: fe3dr-secret-reader
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fe3dr-secret-reader
  namespace: agentgateway-system
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: openbao-fe3dr-shared
  namespace: agentgateway-system
spec:
  provider:
    vault:
      server: http://openbao.openbao.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: read-fe3dr-agentgateway-system
          serviceAccountRef:
            name: fe3dr-secret-reader
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fe3dr-secret-reader
  namespace: db-backup-and-restore
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: openbao-fe3dr-shared
  namespace: db-backup-and-restore
spec:
  provider:
    vault:
      server: http://openbao.openbao.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: read-fe3dr-db-backup-and-restore
          serviceAccountRef:
            name: fe3dr-secret-reader
