apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-tesseract-hub-devtest
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: tesseract-hub
    app.kubernetes.io/component: kargo
    environment: devtest
spec:
  project: default
  source:
    repoURL: https://github.com/tesserix/tesserix-k8s.git
    targetRevision: HEAD
    path: charts/kargo/kargo-project
    helm:
      valueFiles:
        - ../../../kargo/devtest/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tesseract-hub-devtest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
