---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgBEpAkxbbKMVMY9Pttd+GaylZarKqeOEJLj2KDL67w7kU8JD1xCOYOQZGtus7UTKwFzMUF/3dak4nH34xW8OkczDHlw3jkUwkKFLxvdJaB86GyoytdFtXGxh1Nx9ZP5bEQNvqWLyjmOZTEOSnapykG9oaz5pRLAxD1e9tghrRRTg/m4+w8TqQ5pZ5OQRbEYOZeJdSSQINPzCx8STfneeFYHc8Ly1OkJR5MTjAGxpayYsDqmhtvdPRGvvQou2wv1yGeEMhA7k2h/tjhzTDbmL7oBf6fwOU8UlwaQWsDig/VMDuaTcdpDKEZ+XSGFko8o5PtrJT7LvPKAo5sYGQ4FsF7QvSEzfG0OssaZkGb2a4uvoqw/oqg8JWNm1sGJrxZx91nUAPzdA9DNJUmZOpHgMDZ1Kv51JfsdtheGqtMy+lrH221Foa3f8dOtUFKHPMG120+txwFF1gZm8u/xNse8f0tLOeLtdsiyfxivORA/C7pK4Fen1RPlt/NeGAXiPKtP75/ctibiAPInOsM1k41Kqkhwd+K5iD9NKWvDTCGvNKAEuSmofCuMNYfJ8rHlJ+lvO0TO7d5X9xThdF/JpTyRJzOZXQk1NWnrCMexGDk/WC/pGTHZXnX+FapdaDdAhtU6JZ/FtyAg274q/1cJinM/lTRZTCI/eZmJrwmMda0LzZIPWUjYcCnIfJ1vcDDkSOEwAzC7hRJlfS6umJLSFI4WkyDTT0Q7HmODH+6NCylawkB33SY2AwOKUVIzFjNwssz23S+2XBTf4BvffB72Erv45xtpQR9zLBSu9ck08EmXn/xP3UDo36fmLtXBzQxHwivi8qlZ+doZYS1Uv8asDu4s8uRPrBptZkh78IrwUj480x+gkmtYm0dpO63quIOQp8ZzfjPW97gqGWhIbWY6wc6ZX5KCU4BAdqRNzYtY90xBaef8+1nFsMI9XsgTJinWTPeSE2jIaWO+Q53cITPr9un7lWLsg5YfXK+L8c0UpKdN60vZEVUVcozh7RF6J+vzkTwdOXUytdc8dym/gkHvQVM3Dn41RWOWUkM=
  template:
    metadata:
      name: ghcr-secret
      namespace: marketplace
    type: kubernetes.io/dockerconfigjson
