apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homechef-postgres-app-credentials
  namespace: homechef
  labels:
    app.kubernetes.io/part-of: homechef-postgres
    app.kubernetes.io/component: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: homechef-postgres-app-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: 'true'
      type: kubernetes.io/basic-auth
      data:
        username: homechef
        password: '{{ .password | trim }}'
    deletionPolicy: Retain
  data:
  - secretKey: password
    sourceRef:
      storeRef:
        kind: SecretStore
        name: openbao-homechef-api
    remoteRef:
      key: homechef/homechef-api/fe3dr-postgresql-password
      property: value
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
