---
# GrowthBook Secrets - JWT authentication and data encryption
# Sealed using kubeseal with the cluster's sealed-secrets certificate
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: growthbook-secrets
  namespace: growthbook
spec:
  encryptedData:
    encryption-key: AgBvUvAtmvVcqy5hj4CmSH6GcaRzZuyVeLNLCNEhfD7CiHly8WmH1aBO7T5CXr8//cS6KiuJ+5UozxXQqVJxAOktYf8UhaCmeegW1YJvcb+PbEkje97/zdH+lIrCbq8etghwQ9Op1YREp5k23iL/TrgE5T0ayIji7CTY6PLpGUlCwYj/NknDmOc/kC1qMi4jZ0fpgVQg8TWZy345eiz9Hs9kuSaRZjQ6x86FGhwz2kC+kx7eCPoXjrMCE7NFdMHSVKkjW8I7KJgyauiFkBM9NSicbRUo43yQOveA4RBXj0c2dabTtQwq3e/aAIY8GXJn4OjdBLEKHcPRZOrmIiDARfuPU2E7Le6Ri2PTYz4tb1Cmy2dkgsVP5kdno7c20hFX2eKndibKp5v4fw3crRKjnvKr77Mqg+rBEbcfsALKXdGSJ+rklR2mySZ+X5v6WJfK158LHE12H7I7dWDCjl811vqAXHweth7RLD7GZHqm2pZyz+o0b8H6HJdYHJ4LMEvnK+DLssUsL0Fsy2XdIoV404tpnJgdBbafndIlHAthDtUqK7GrxL12RH7qciry3p9riZEdvdzoS/e7w/epKoY1A1AHWL0DfKx7v6c+4FS/naCdfisRoy5B3YXBqS5LN4v9hMJLPaR/a2rxmC20p1vmCCSUeAtye0ZE0lD//cQ8+/u8FzhdTjsAYujssxprew5mpHLOHXmEtyGXH2rdSuLHFoGUzuu7yQt0dm/yFrF76E4h3metWrKzSN3H0/LnJ5iqE3uLr6Z62+aClQTLp1ZhUjlj
    jwt-secret: AgALRHDl5dkOc8AZQ41xyLg3L1Ve5mG4hFjXZwUl9grBp9Lv4Nw4DnzN28uEkfOmRRemaDxx/YSIjPt0edQoyNCjQHpxsmMKhoyvXiBDxXFDPFXeT4y/etf2OCYoEOzGSreOxkIFBSwpbpKJXKv1rRqGRYlpa5fuCV970kTFyiX5JKd0PBRj/kKgIb2IsT6WrAUQf3uFmZvHRcArJxelxtSoEbiCXYLG+GrXYyC9lTAKJMajCyM8/2xq6B3Z56yRxv2nPHBIEmUuVqKfuc1n5pqfAQNi4UD1GfrihCwD/GfwpAfW6TwZsq54MssUGcZkwaVajxEkXItNvY5zs/6JTjDvWVeuhF9CUV7AK7XKn7qMzEXGSxu8ea21mBkCqi5w/fpTztuKRcgu5yim20ek5GSA/ZCgvTUhXFsqcpm3bT3PD3dgz9s1QxEmsiDtHvJcbZVq3/9zxJnbQFM8jqNaEkniD79/dxd+7tcsDBghwY0PqH3DdcAlaU+xDOrQ5IHFHRTqKyu1v/OGBLYH7OcHcplIAbnaraFU0waBpfVYfAA+ffPbu65UwyXEMaTUkwfeuRHs3w9kEXS8tkadkFWirngjhlRRsBFtFr5Hgp1zgfc22zHABZxnh854XwDsGLy4q934/9wJmWxdqwth8vyIC+1UCaGq3UOei7EixVDYVwzGHFH7O4cNcA1S3ggJrcKn5JYswhWAEmg0oiFECnsXTAVxtiuSzB8vPZ88AZKHdtR3ekfOZvZiUJNlSGk82Qc8r2ytHuiDufen8iT5ABskAfao
  template:
    metadata:
      name: growthbook-secrets
      namespace: growthbook
    type: Opaque
