---
# Keycloak Admin Password SealedSecret
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-password
  namespace: identity
spec:
  encryptedData:
    admin-password: AgDoTRxORno9t+jXuH7jKwUImNFWxW6++PYF4GDzQUR9a9J+wczd+aEejaKIIXiBIcgTv7sgUMOdlLXMUppDLh7K7pYY1Wvvxik7g8WHcQVCen56q1IVbHGjx39LsyMBN1iXkucyUfwB22VhsjUY0KWdLHnXKU+R07tcX/5Uak27+yNTev6j3NRCaQ3kIVRo6gSIgvSMALLUV0HIT6dCFiyXNrNGszP7lyV2S+EBat6I/6y1wMDlkc/X0V0pp4m8agsWBsp1f8fgqI59/zHm0C5Tx2XDUhsKh6GKisdujhKqIhhT5jlIAinwRG0LHqiHiBcrU14mqVrARUEe8/bVmkUpNurcl1lfzz7TIeb1Ia2qq61Y924K5D7NvELz2HZaMyeiylRtB1G81INGu7wKty4LdteBueYw2k+FZVXlAKldRVUlvEtFJI84sCAmDIr4H3a6NtxfxqZut+XY7RsSgS/v3pTlZU1q4byAldJgwIjY+Zhepei9+ZltvUeyNpTIsvc4EdBGUmtmql95XBUtkCMVDfAzboGmsmxauOfSzPhdTRjY+uTb2dSZu7MnLcsiMwoDOwagsOYBYjd7m2sCROMtcAbpyTWLGgjMlctW3diJALjcSH8Baa09E3JzBBFmL/hTxsUf8ZJ/Kxz862L1717sOTBZhGLsvfRoD8RtVjTblFAICiu57kjWwJHkuFOUc0rVCZOrcCr0W+yLjZBhIoEelO3Okln8vVg=
  template:
    metadata:
      name: keycloak-admin-password
      namespace: identity
---
# Keycloak Database Password SealedSecret
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-password
  namespace: identity
spec:
  encryptedData:
    password: AgCjqb0sbA/5F9Zb3AvEx7a4Z5ew8UTub1vFEnN3BWl+fGNUlb4u0yhIfJ5K1NWWH8c3WZQDjDLsCYy6QUheS3wJrTLYiqSwb8eQuTyyGj3/VnOg5qOTh3Z24tsJEQNWJCgENQjSEOtzFwxNP/uQdISlDxrh1KXHko/PNayFTNGL1v5ZAo/Vb/BzXvVApenokPOBjBcdl8WKPihuRu67IvZqrUC/eycoRUGcRWzui+qh/A9ThoSDAMBtYmU5FokEUsqlVzETmqt1vLDw6MqS7b9XoqcbW/Krc0Ee2l2N16GNfCo+JXUqInLle2ZsTAQ/+YAEAB/OxQCcC0L+utxKihHD9W1qVOR0JHyzY2rZ3b50JYJWCJ10D5cWf8oj3G+5cX2NYBUfOwJ23X58z4Yy8ItKCmn9fJXUVUgnt99Prp6A+SHPBTnq+8bl72Fnuu0eeyBWbzKxjQ8ziI8ZkOqjaOWkev/wdQ9QrnH1oHXt2uqFI7+iHhDao7zM3yZxq81ExfOSDN0IsPRFWIjuT/KDVTxNVxAc+JxY4GdxQPVxbYAQx8Gls/0Sjb+M0ua0CD7hTxUD4lxW5P91F/7vgxQRXDSLxjxGblur1Zpeuat3wTFSkwiDgTWkG4lcr9Is/Fur6DHnWD2u2UfhiwEQ3VaCiWccYZZL9qZ2J6nkwacgGV+LOhtnltCfeN035x0K2UWwUKzaUeegPMFx2gK4gg7Bj2hI6nBD/IMsRbw=
  template:
    metadata:
      name: keycloak-db-password
      namespace: identity
---
# Keycloak Redis Password SealedSecret
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-redis-password
  namespace: identity
spec:
  encryptedData:
    redis-password: AgBefCjtfjJ4UqiexddGwAn404j8V+ieRQmEVyyfw8XNcsHv/HBmlczlKgj2a/pZ0C98spJvafJ/392k+ulEvGcBONiSa22syBMmpuwKcdeY8oI/iESXlBM2/rlnBgW3hFTkHtxgPKz3M7v5uy26/KA9g0JrOqLHPvEFLRyEtHljUFE6E1X7Q4I5R6FAeFOd14EDpbCytJwnltCLsgo4nM3QIFhitzBFjLiayyccle0d2I70EeKkdz8r+FK4AxDblIym7cVptd0OpiH7cY+RkWK9+L42LTopUhSor/0SdjIOgX636szcHqPnYewfHNmRT6mGYdg2Kcbkb64B3QIgrqnYtonXmnDiGBulP7Ugy9qxj1hAr8DPnY4ZBq5JkvOPbK7vc/xgPF6KQUAgcd/4knkUDZ7bEbBz0DBHtF8V6ObK8YJtY97GWO5I2cNK325GPDtm/hAcAw+a/wcnTdSECcWbaU3vpQ/zPjelJDU5dZUBHGKrna+uhMVTe0tDDPmLGunZehCvFftcTAb7snPSfi60xLCfOf28QHdSX87bQ2P+/GOMcFL1NtZ6xW6w4i1YWKU5+O/+KO1TZ2+LFHt4TQJO/SoHxG3RqdcggeNPtn/b2jDisWJzYz+pZ3O83jMUw2cWZYu7KMN/JdrvA37OUvuxoxv8WTDFX5rC9Gb3Nuwvt9f9/Jd1CLDSOsI5Fw3BKnV6j/U3EKtthA==
  template:
    metadata:
      name: keycloak-redis-password
      namespace: identity
