{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "petstore-api.fullname" . }}
  labels:
    {{- include "petstore-api.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "petstore-api.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- with .Values.autoscaling.customMetrics }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.scaleDown.stabilizationWindowSeconds }}
      policies:
        - type: Percent
          value: {{ .Values.autoscaling.behavior.scaleDown.percentPolicy }}
          periodSeconds: {{ .Values.autoscaling.behavior.scaleDown.periodSeconds }}
        - type: Pods
          value: {{ .Values.autoscaling.behavior.scaleDown.podsPolicy }}
          periodSeconds: {{ .Values.autoscaling.behavior.scaleDown.periodSeconds }}
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.scaleUp.stabilizationWindowSeconds }}
      policies:
        - type: Percent
          value: {{ .Values.autoscaling.behavior.scaleUp.percentPolicy }}
          periodSeconds: {{ .Values.autoscaling.behavior.scaleUp.periodSeconds }}
        - type: Pods
          value: {{ .Values.autoscaling.behavior.scaleUp.podsPolicy }}
          periodSeconds: {{ .Values.autoscaling.behavior.scaleUp.periodSeconds }}
      selectPolicy: Max
{{- end }}