version: "1.17.0"

highAvailability:
  replicas: 2

# Default channel implementation
defaultChannelTemplate:
  apiVersion: messaging.knative.dev/v1
  kind: InMemoryChannel

# Default broker class
defaultBrokerClass: MTChannelBasedBroker
