apiVersion: v2
name: bookkeeping-report-service
description: Reports and Analytics Service for Bookkeeping application - Go microservice
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
