{{- if .Values.rbac.rolloutRestart.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "company.fullname" . }}-rollout-restart
  labels:
    {{- include "company.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
{{- end }}
