{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "company.fullname" . }}
  labels:
    {{- include "company.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "company.fullname" . }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
    {{- range .Values.keda.triggers }}
    - type: {{ .type }}
      metricType: {{ .metricType }}
      metadata:
        {{- range $key, $value := .metadata }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    {{- end }}
{{- end }}
