apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: tesserix
    app.kubernetes.io/component: terraform-automation
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/tesserix/tesserix-k8s.git
    path: charts/thirdparty/atlantis
    targetRevision: HEAD
    helm:
      releaseName: atlantis
  destination:
    server: https://kubernetes.default.svc
    namespace: atlantis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
