apiVersion: v1
kind: ServiceAccount
metadata:
  name: homechef-database-reader
  namespace: global
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: openbao-homechef-database
  namespace: global
spec:
  provider:
    vault:
      server: http://openbao.openbao.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: read-homechef-global
          serviceAccountRef:
            name: homechef-database-reader
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: global-postgres-homechef
  namespace: global
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-homechef-database
    kind: SecretStore
  target:
    name: global-postgres-homechef
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: homechef
        password: '{{ .password | trim }}'
  data:
    - secretKey: password
      remoteRef:
        key: homechef/homechef-api/fe3dr-postgresql-password
        property: value
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: global-postgres-homechef-platform-admin
  namespace: global
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-homechef-database
    kind: SecretStore
  target:
    name: global-postgres-homechef-platform-admin
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: homechef_platform_admin
        password: '{{ .password | trim }}'
  data:
    - secretKey: password
      remoteRef:
        key: homechef/homechef-api/fe3dr-platform-admin-password
        property: value
