apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-bff-secrets
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: auth-bff-secrets
    creationPolicy: Owner
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: prod-global-redis-password
    - secretKey: PLATFORM_CLIENT_SECRET
      remoteRef:
        key: prod-platform-client-secret
    - secretKey: SESSION_SECRET
      remoteRef:
        key: prod-csrf-secret
    - secretKey: CSRF_SECRET
      remoteRef:
        key: prod-csrf-secret
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: prod-encryption-key
    - secretKey: COOKIE_ENCRYPTION_KEY
      remoteRef:
        key: prod-encryption-key
    - secretKey: BACKUP_CODE_HMAC_KEY
      remoteRef:
        key: prod-auth-bff-backup-code-hmac-key
    - secretKey: TOTP_KEY_DERIVATION_SECRET
      remoteRef:
        key: prod-totp-encryption-key
    - secretKey: INTERNAL_SERVICE_KEY
      remoteRef:
        key: prod-auth-bff-internal-service-key
    - secretKey: VERIFICATION_SERVICE_API_KEY
      remoteRef:
        key: prod-verification-api-key
    - secretKey: MP_ADMIN_CLIENT_SECRET
      remoteRef:
        key: prod-mp-admin-client-secret
    - secretKey: MP_STOREFRONT_CLIENT_SECRET
      remoteRef:
        key: prod-mp-storefront-client-secret
