apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tesserix

resources:
  - ../../../bases/go-stateless
  - external-secret.yaml
  - configmap.yaml

patches:
  - target:
      kind: Service
      name: SERVICE_NAME
    patch: |
      - op: replace
        path: /metadata/name
        value: auth-bff
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: auth-bff
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/configMapRef/name
        value: auth-bff-config
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/1/secretRef/name
        value: auth-bff-secrets
      - op: replace
        path: /spec/template/metadata/annotations/autoscaling.knative.dev~1minScale
        value: "1"
  - target:
      kind: ServiceAccount
      name: SERVICE_NAME
    patch: |
      - op: replace
        path: /metadata/name
        value: auth-bff
      - op: replace
        path: /metadata/annotations/iam.gke.io~1gcp-service-account
        value: sa-auth-bff@tesserix-app.iam.gserviceaccount.com

images:
  - name: PLACEHOLDER
    newName: ghcr.io/tesserix/auth-bff
    newTag: latest
