{{- range .Values.namespaces }}
---
# Default deny all ingress traffic to namespace {{ . }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: {{ . }}
  labels:
    app.kubernetes.io/name: network-policies
    app.kubernetes.io/component: security
spec:
  podSelector: {}
  policyTypes:
    - Ingress
{{- end }}
