apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: identity
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  sourceRepos:
    - https://github.com/tesserix/tesserix-k8s.git
  destinations:
    - namespace: identity-customer
      server: https://kubernetes.default.svc
    - namespace: identity-internal
      server: https://kubernetes.default.svc
    - namespace: zitadel
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
