apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure.yaml
  - identity.yaml
  - data.yaml
  - platform.yaml
  - marketplace.yaml
  - fanzone.yaml
  - homechef.yaml
  - hms.yaml
  - bookkeeping.yaml
  - tesserix-blog.yaml
