apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure.yaml
  - identity.yaml
  - data.yaml
  - platform.yaml
  - fanzone.yaml
  - homechef.yaml
  - tesserix-blog.yaml
  - gameverse.yaml
  - dwellm8.yaml
  - scrapper.yaml
  - stockpilot.yaml
  - guardix.yaml
  - social.yaml
  - release.yaml
  - horoscope.yaml
  - postiz.yaml
  - kora.yaml
  - governance.yaml
  - ai-database.yaml
  - security.yaml
  - planning-poker.yaml
  - vehicle-rental-app.yaml
  - helivanta.yaml
