apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: scrapper
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  sourceRepos:
    - https://github.com/tesserix/tesserix-k8s.git
  destinations:
    - namespace: scrapper
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: networking.istio.io
      kind: '*'
