{{- if .Values.createServiceAccounts }}
{{- $c := include "document-intelligence.config" . | fromYaml }}
{{- range $role, $name := $c.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "document-intelligence.labels" $ | nindent 4 }}
  annotations: {iam.gke.io/gcp-service-account: {{ printf "%s@%s.iam.gserviceaccount.com" $name $.Values.documentAi.projectId }}}
automountServiceAccountToken: true
{{- end }}
{{- end }}
