apiVersion: v1
kind: Namespace
metadata:
  name: tesserix
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: shared
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: marketplace
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    istio-injection: disabled
