apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Global namespace secrets
  - global-secrets.yaml
  # Company / tesserix-home
  - company.yaml
  # Identity
  - identity-customer-secrets.yaml
