apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - scrapper-api.yaml
  - scrapper-web.yaml
  - scrapper-identity-bootstrap.yaml
  - stockpilot-api.yaml
  - stockpilot-web.yaml
  - scrapper-istio.yaml
  - stockpilot-istio.yaml
  - stockpilot-db-seed.yaml
  - openbb.yaml
  - fingpt-inference.yaml
