apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scrapper-web
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: social-media-scrapper
    app.kubernetes.io/component: frontend
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: scrapper
  source:
    repoURL: https://github.com/tesserix/tesserix-k8s.git
    targetRevision: HEAD
    path: charts/apps/scrapper-web
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
      parameters:
        - name: image.tag
          value: "latest"
  destination:
    server: https://kubernetes.default.svc
    namespace: scrapper
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
