apiVersion: v2
name: verification-service
description: Verification Service - Go microservice for email/OTP verification
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
