apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gameverse-server
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-gameverse:prod
  labels:
    app.kubernetes.io/part-of: gameverse-platform
    app.kubernetes.io/component: backend
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gameverse
  source:
    repoURL: https://github.com/tesserix/tesserix-k8s.git
    targetRevision: HEAD
    path: charts/apps/gameverse-server
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
      parameters:
        - name: image.tag
          value: "main-120acf4"
        - name: ingress.hosts[0].host
          value: stayandplays.com
        - name: env.CORS_ORIGINS
          value: "https://stayandplays.com"
  destination:
    server: https://kubernetes.default.svc
    namespace: gameverse
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
