---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgCNoG8enU/tmHnlvTOv+WrlgITngnGmgPxnY7BjakKmOlRS4JsMJ+BklJIFuselH9PZM3yXlJv1LOo0N/WzM4NaOlbmEPS+9NBWHz9HMPKdm7IRZ0/cR3FC9lnAmkBuXGowM9O6iTwPUZlvVK4McwLQSUe8rIlhXyiCQ+KIDEvy4QJfH9T0iWvf0k0ZhqWvy+4wY0SAywcYM59KTr050aw8iQLAv+H4K2tkf5qzl3zggFiFeDa8a6hydKyittdUvFOP+N576hqwmeTEzmxJ8pStiQmlx3VQYSpEEuBB4wTD8UiFGtsRpPRkwRk67UiHNs9BVyQccKzu8Ts8neAqeWJ2Ll0Pn4bsYMOgSG+sqWD7zBv/QbUpWluq2RQPqCV+zR5BgCvNWcJQ1Wu0dMfAedtW5MGafCvSw+Wy3vm9K+0AV3Aophym5Y08qrkgpNyHDrbtV9B50uHfjemEl5zkLE45VlFQKsN6Me4dpCcoSeHkJCym8YAEhrRnWYcl8hTVXm2H5XFb9MNS2vM3RmTqG9tedozvuWZSk3CtA7X070DmKB1u06gwXHRT4O49VZz85Wx32dVAb45V34MwDEPLHgefyHR55Gy0PayHj0Fjzu2B2obl7nCKOqJq3zrX9u/G4u6gpptHWWxrKJxW/QOR/oqqlyL+aN/Qc0esANNfc85Aa0+zi+U0x1SbF+k9HJR66U2FpFV06Soa0s914S2dEF9U3Y+6YoD2xW3GhlWUNwTfMwdR6wwv+kw8
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
