apiVersion: v2
name: fanzone-media
description: FanZone Media Service - Emoji catalog (OpenMoji) and GIF proxy (Klipy) API
type: application
version: 0.1.5
appVersion: "0.1.0"
keywords:
  - golang
  - media
  - emoji
  - gif
  - fanzone
maintainers:
  - name: FanZone Team
home: https://github.com/FanZone-Battle-Ground
