{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "fanzone-sportsbook.fullname" . }}-secrets
  labels:
    {{- include "fanzone-sportsbook.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef | default "gcp-secret-store" }}
    kind: ClusterSecretStore
  target:
    name: {{ include "fanzone-sportsbook.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: prod-fanzone-postgresql-url
    - secretKey: JWT_SECRET
      remoteRef:
        key: prod-fanzone-jwt-secret
    - secretKey: MONGO_URL
      remoteRef:
        key: prod-fanzone-mongodb-url
{{- end }}
