{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bookkeeping-invoice-service.serviceAccountName" . }}
  labels:
    {{- include "bookkeeping-invoice-service.labels" . | nindent 4 }}
  annotations:
    {{- if and .Values.gcp .Values.gcp.workloadIdentity .Values.gcp.workloadIdentity.enabled }}
    iam.gke.io/gcp-service-account: {{ .Values.gcp.workloadIdentity.gcpServiceAccount }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount | default true }}
{{- end }}
