apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin-password
  namespace: identity-customer
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-admin-password
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: devtest-keycloak-internal-admin-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-password
  namespace: identity-customer
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-db-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: devtest-global-postgresql-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-redis-password
  namespace: identity-customer
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-redis-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: devtest-marketplace-redis-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-idp-google
  namespace: identity-customer
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-idp-google
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: devtest-google-client-id
    - secretKey: client-secret
      remoteRef:
        key: devtest-google-client-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-apple-sso
  namespace: identity-customer
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-apple-sso
    creationPolicy: Owner
  data:
    - secretKey: team-id
      remoteRef:
        key: devtest-apple-team-id
    - secretKey: key-id
      remoteRef:
        key: devtest-apple-key-id
    - secretKey: service-id
      remoteRef:
        key: devtest-apple-service-id
    - secretKey: private-key
      remoteRef:
        key: devtest-apple-private-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-facebook-sso
  namespace: identity-customer
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-facebook-sso
    creationPolicy: Owner
  data:
    - secretKey: app-id
      remoteRef:
        key: devtest-facebook-app-id
    - secretKey: app-secret
      remoteRef:
        key: devtest-facebook-app-secret
