knative:
  minScale: 0
  scaleToZeroDelay: "120s"
  enabled: true
serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: app-secrets-marketplace-prod@tesseracthub-480811.iam.gserviceaccount.com
gcp:
  projectId: tesseracthub-480811
  secretManager:
    secretPrefix: "prod"
db:
  name: marketing_db
  user: postgres
  image:
  tag: "20260329-fga-preshared"
