apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kora-ai-agents
  labels:
    {{- include "kora-ai-agents.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.storeName }}
    kind: ClusterSecretStore
  target:
    name: kora-ai-agents
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: {{ .Values.externalSecret.serviceApiKey }}
    - secretKey: GATEWAY_API_KEY
      remoteRef:
        key: {{ .Values.externalSecret.gatewayApiKey }}

