apiVersion: v2
name: hms-crm-service
description: Hospital Management System - CRM Service (Leads, Campaigns, Feedback, Roster Management, Promotions, Jobs)
type: application
version: 0.2.0
appVersion: "1.2.0"
maintainers:
  - name: hospital-management
    email: devops@hospital-management.com

dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
