apiVersion: v2
name: fanzone-prediction-bot
description: Helm chart for FanZone AI-Powered Prediction Bot Service
type: application
version: 0.1.2
appVersion: "0.1.1"
keywords:
  - golang
  - prediction
  - ai
  - anthropic
  - bot
  - fanzone
maintainers:
  - name: FanZone Team
home: https://github.com/FanZone-Battle-Ground

dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
