apiVersion: v2
name: mp-payments
description: Marketplace payments service
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: marketplace-common
    version: "0.1.0"
    repository: "file://../marketplace-common"
