{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: sre-ai-agent
  labels:
    {{- include "sre-ai-agent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "sre-ai-agent.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
