apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookkeeping-app-of-apps
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: tesseract-platform
    app.kubernetes.io/component: bookkeeping-services
    environment: pilot
spec:
  project: default
  source:
    repoURL: https://github.com/tesserix/tesserix-k8s.git
    targetRevision: HEAD
    path: argocd/pilot/apps/bookkeeping
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
