apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mp-payments-secrets
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: mp-payments-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: prod-marketplace-postgresql-password
        version: latest
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: prod-mp-stripe-secret-key
        version: latest
    - secretKey: STRIPE_WEBHOOK_SECRET
      remoteRef:
        key: prod-mp-stripe-webhook-secret
        version: latest
    - secretKey: INTERNAL_SERVICE_KEY
      remoteRef:
        key: prod-mp-shared-internal-service-key
        version: latest
    - secretKey: OPENFGA_API_KEY
      remoteRef:
        key: prod-mp-openfga-preshared-key
    - secretKey: OPENFGA_MARKETPLACE_STORE_ID
      remoteRef:
        key: prod-mp-openfga-marketplace-store-id
    - secretKey: CREDENTIAL_ENCRYPTION_KEY
      remoteRef:
        key: credential-encryption-key
