apiVersion: v2
name: fanzone-fan-connect
description: FanZone Fan Connect Social Service
type: application
version: 0.1.2
appVersion: "0.1.0"
keywords:
  - golang
  - fanzone
maintainers:
  - name: FanZone Team
home: https://github.com/FanZone-Battle-Ground
