---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: keycloak-idp-saml
  namespace: identity
spec:
  encryptedData:
    client-secret: AgBNwr71f/PO3IJL1yRLx3AGr4y+UeEzqIE37FOz33bPclspR4pS7fn73jpz75I+VryDLfR/M+5qOIPOSMoEzbV59W4BHpGEeEtq9za0txDdywvFgRnAVlHHtYEKJI1/2kYNSMCXxVqBjOq8+j5muaOu338ufiy8C85OpCHhj7VYJrBvW6/lAP5yu4PEcoOh11K0/T1YUg29HJfCJbp4oOnelvlg7TwbFxHBeApBLm2YmET58AE2XXcQ33BxAlw3Abil6xqWu7t1TgEAqoUeocRH2gfClpxtv8TV3w8vlPbUYOoo1qU7aWmHVaOy54groDpoXJiFX3IgDlFHznO9IO+n6UENPsGxm45zIIfpyk/2P0OReapjPpVEBniSgsvghSD6GkDsWodrs+JpTVLR3K8E/36BIx5Cj5gZG0GR4zrPAvvrMUs/9KpycNddL9e5ucQdF47pj4X0mzhQIrVo0nJrpMoreJXx9Cz2VFW4n2MEWFKWiE38Und2vOlsKTS4cmUHno9eDlroprcGJLsmFSfpFOe22YYfoUnTenQ3sZ28F7eb3qvys3IT4yNHIoS0GeogZxKTpNtnkgEZmXbq/Me2Dv0/knX/feIpIWrsmZ+bpnf0Y/xT/VGOoaNOVMPkni9cENwf13hQRhIPZa3xMP+3ixdkAa/j8hc2owHJJtXqgNyyX59vCPY8b/JvHsb/IVt/JASPy7O5aTPwCgt6BzdDUQEpFyMkTqRmJ0j7xQDiAqrc9g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: keycloak-idp-saml
      namespace: identity
