apiVersion: v1
kind: ConfigMap
metadata:
  name: mp-shipping-config
data:
  ENVIRONMENT: "production"
  GCP_PROJECT_ID: "tesserix-app"
  DB_HOST: "postgresql.postgresql-marketplace.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "shipping_db"
  DB_USER: "postgres"
  DB_SSLMODE: "require"
  SERVICE_AUTH_MODE: "mesh"
  OPENFGA_URL: "http://openfga.marketplace.svc.cluster.local"
  OPENFGA_AUTH_MODE: "mesh"
