apiVersion: v1
kind: Service
metadata:
  name: secret-service-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "secret-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "secret-service.selectorLabels" (dict "component" "secret-service-api" "release" .Release.Name) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: secret-service-web
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "secret-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "secret-service.selectorLabels" (dict "component" "secret-service-web" "release" .Release.Name) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.web.port }}
      targetPort: http
