{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "audit-service.fullname" . }}
  labels:
    {{- include "audit-service.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable | default 1 }}
  selector:
    matchLabels:
      {{- include "audit-service.selectorLabels" . | nindent 6 }}
{{- end }}
