apiVersion: v2
name: tesserix-blog
description: Tesserix Blog - Technical engineering blog powered by Next.js
type: application
version: 0.1.4
appVersion: "0.1.0"
keywords:
  - nextjs
  - tesserix-blog
  - blog
  - engineering
maintainers:
  - name: Tesserix Team
home: https://github.com/tesserix/tesserix-blog

dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
