{{- include "marketplace-common.knative-service" . }}
---
{{- include "marketplace-common.configmap" . }}
---
{{- include "marketplace-common.externalsecret" . }}
---
{{- include "marketplace-common.serviceaccount" . }}
