apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "support-platform-mongo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: mongodb
      port: {{ .Values.service.port }}
      targetPort: 27017
      protocol: TCP
  selector:
    {{- include "support-platform-mongo.selectorLabels" . | nindent 4 }}
