apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marketplace-app-of-apps
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: tesserix
    app.kubernetes.io/component: marketplace
    environment: devtest
spec:
  project: default
  source:
    repoURL: https://github.com/tesserix/tesserix-k8s.git
    targetRevision: HEAD
    path: argocd/devtest/apps/marketplace
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
