serviceType: go
port: 8080
healthPath: /health
nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/tesserix/mp-approvals
  tag: latest

knative:
  enabled: false
  minScale: 0
  maxScale: 5
  concurrencyTarget: 100
  containerConcurrency: 100
  timeoutSeconds: 30

probes:
  startup:
    failureThreshold: 10
  liveness:
    initialDelaySeconds: 15
    periodSeconds: 15

serviceAccount:
  create: true
  annotations: {}

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

db:
  enabled: true
  host: postgresql.postgresql-marketplace.svc.cluster.local
  port: "5432"
  name: mp_approvals_db
  user: mp_approvals_user
  sslmode: require
  secretKey: mp-approvals-db-password

openfga:
  enabled: true
  url: http://openfga-direct.marketplace.svc.cluster.local:8080
  authMode: preshared
  apiKeySecret: false
  storeId: "01KMS970NNJPJP97MR7XNZSVD3"

externalSecrets:
  enabled: true
  secretStoreRef: gcp-secret-store
  refreshInterval: 15m

extraSecrets: []

env:
  STAFF_SERVICE_URL: http://mp-staff.marketplace.svc.cluster.local

gcp:
  projectId: ""
