apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kservice.yaml
  - service-account.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: tesserix
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
