---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postal-credentials
  namespace: email
spec:
  encryptedData:
    secret-key: AgBT93in/H0OtLA1XwoKse5MyfKK9mJqXAL2VtcakabisriSAOUi9PlwNA1+H1MwAlqvvlaDXAfD1B17lZL2o/Gj7xkOHRaHxSZolxgRxCWrYFOuf43w2EIdM7n0W830YBimKSjp60wRzBrNBD+NwCkNhIGDsGzdQh1Ca7LWsbCjVz3DD8p4IPoCAsExoZxRWmZU3GHdKEKpFNJZfNKdaFR36XTQFYT9g03I1czOr45/IhOE1Onf/A/hggF12N1upF9PZhTap1IBitLjxP59KQLafGLCpmo9gjkVlUrF9Lcl9EsaHPgL5gj4gdmpxLp2qIqbWysv1TzvJX+nqIR5yXYo/YbWpsk1xDlj8buhzJ4QB4SpLyE3l98+P1bDe3jkJq4M+NsUgocn+AK9Xc0VgLOpV1qm/pmuAxUGda69Hmrb3u0WJZ4kLYwIY1G345Tsj+sga2Hq8SDeEG1EqQj5spVo/d3M3DuMvwRxoRnAMLYCe8qUzZ2VQ0KpTCXNUmneYtQMFA38pTjBY4uHvAxzvObGM0MezzxT67vUk8GT2CaLqUufgulP2klDjUR/IU4iFha5Q8svMMECc+XMvRbbQW9RmXIPTKejDU5+NGm0Oa0D/t3GShifYm92n9Om4+WCbG9m3WfIeXjkFE7akHZ3Iq2Z/1hDQz7yOuaylghq6rDDozFF+zH8TYq0OZVZM4tqwPjTv+ZbpKOZMoUY7IKvwdWKHSfZjivxPhbJjHNGNs5eNYvKXixMxHQI5zC97w9oWXH4aT0MA2Okjyokq3yIdLEQ2ahhcYtVpZU3F/4h7PmMGb7PUc96ZdcWgLY8EamyWauFr2aT3q1MaKB/Kk6of1C86Tequ0Gi8XegryiYEzLFHQ==
    signing-key: AgB/KQ1cBX8tbq8UImsNK+Ppc0e4qt1/O4wTwrdccECjV+1O6zr0EAhEUZEC1ZhJS1WzPszX39E6Siacjum/cgFtfMjGMmu4d3qN0Cp1cqI3zIgCDEMlDlunapf3iUxeSstUB4rH4ZFZbnKkDrnOcpIre2CpHu33HWL94juUAR0oRYZYO0KDvmuouhkuor5TjwVnaU9s10QcedHQhW3oRIwpjK3L4SGDzdaQcOSjgoVysJ/+4jSBc3VIwoMR/BVKwRrcvcSWg10d/Kn6/WbWN2NF2/mnVI6fGUV7gvFwXfQHC/P2La9vQ7WlxpvwXUNAB6CDcDnoS/EFm2U/D7GktMYp9TIzSDyjZQ363Y5wWT4VgYzDrq82YtTq25INFBa+4sv9g9okC63fmPDuHu45+LBiCxzkdFbKKajdIr8OOLlGvE7vpCG9EH43ofYgqsZGxjK+m8P6tWZBcD1ddiju+YRkKxqcOvoa6rhPDwXF6xKLux7Wh4iovIbkrGj2aHvqpzclNfxL7w+XmOLXcowtCJs01Z5VQINZTYXystYITAoR0vFWWHav6jwMn/spYkC5ZFc8FCywmqlJkrqrbc+j/qKCXiRVgJLgNutVJbljsaLvY2rpHZwT+yH8D2NpciY7Ozm3v+5rmKJUfUFdk1P//VBop9OxxnyR1CgGxIV2JCE+N+vNAUES8qORBMZCaw/jGrj5N3gqx7EpFtVm9XQkBalW32wLgeVZTewZcL5lGkwxAiQQmYjj+9XSOHhnaOV7vBGGNZ4EHlwfvfQ6iItqX2Nj4AuUGRiUTdKGUcnfRe7zDZTNlysF+fDcz2O7SvdzK8GwdhxPsHKe4GhDjoxW1egTTmsCkOZ0JNmy4iCajozLFw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: postal-credentials
      namespace: email
    type: Opaque
