---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postal-smtp-credentials
  namespace: email
spec:
  encryptedData:
    password: AgBKDib9wWXCzdRLwNtqr2W4nQeuP7kF+4IS1uYDcE3jGMb/Cks6s9qFYlHdij/DkZld/gcOORMqWkF04BGMRtWgYwyj88H55TUP1q7vrc3nAgj0vtfL8FEfvlfDNEDIh4eg4VomYIkiKlYiUJX5EpO/2Qky/0Gi+ae3B5q0UEnyG8pH6JqHk40HRlxjtsNhLOQIT5llEmIfu4NmKyYR8JD3EHWzpt99JsKrtdSs+XH55iJwY5wpAD2MvKonSeU2x0O9t9/TsZ+NAkBfpuXT7uifuUp/71XP3Pw19RWywcKev8/w43FJv1jNO1hETb3wURUK6Cy/P+Bk7jNOF4aBCpVJokPAYK1mp1O0jHxO67hyOk+U+6X1Gw0+lD+3/aKd5D0pXmx7AasLR7qTgFLWAbbQsk0nfPeAx8OcGrvjpXFGxptodmTH/Aah1gVi1LXFuyXE3Yg0nMjmc/YbVfqghtc3nLXl0L3hQEXuqp/kUzCFrB1Be02e7O8EQECo0XKzxNeQlRc71d01mslO+SSMtP+qtU5jPK3HixMQq1uzU0cAJru5xba4Rp4cyiDq4JYO0SfLLm6TF1f716xfbLM6UD1Md6rVVwcZfEaoJyyKG41grvoS+Tj+9Pu7hDhDsvG1VXkVi1n12Td7EZQ+9esKsN+18YYqgroIdEYuWbTmOtqPwJO/pQZhFbPr875rtQf+tkowvXPF/U0+QI/flEtqjNoKIPjkTvD7KiJI7PJSYGeIy/Mv9zcoZHOGHSlOF3qk
    username: AgAOBZSONLXMGmNrGwbJ9V/QXZnVGn2WZq/uyS5p+NSvCytM5SpAt6fBwfc/N8kYwVGVGXfcAj+Ov6m9H3wJx/ecv/bNhOlr/i9Mc8XSkQKdGdKleX+GDTf/wyhOcEWhH8Y6kEStbmA0+nhoWAUP+93wLCLiAnI8PoYVAw/pTfMdPThdh97/5wHsy/JrYLnE9VemenjpgEXdb1FbRdRElbw0xLJ1XZCerfbKdL6Rx9r3E9VQn6EHRQoQ/Z/5hY/1CeR+achuEBECKwjvzaCAhvGiw/uI48UPP3RVtI2ftqXL/X4gKH6k85xDcsV9WF4HMuxusGFWgVLt2C+zAqHpPrglL8gpWSx62s9VIQ1dwYYSPUmB3jmMxcwI5iexf1Uzkq61yz3xfKmDxeg1jMC7H4gjAavfx8sedCea5Axvbxh1GFFSWrQfdiu4M4ftdOqzuseJ+FiplYHcXtvjbJVNwsff0WxGvrx8FwqZvdzYdNHrFmeaoU135//zlmsagl+d8bImIs5DkSnNNvw5bFisQt3wH5KL4MnrpClhq3WNBE2fdE4enL8WVynkndA7TYI8Uf6hDnxLMRFcKHh21ZbqSAJkysvH0JaFSJ3ccu6XtRikMrc83IZfiIvMC08HmMpoAPSsk5I0kYz5iYPCISkKKoPq+l4GBdj2TbVMiozsyf8BMFINnCFkRheRnSe5f8MNopkRLVh8A9rQPmgusOU1vg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: postal-smtp-credentials
      namespace: email
