---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: rabbitmq-credentials
  namespace: email
spec:
  encryptedData:
    erlang-cookie: AgAVBpX/twDYp10fAbpTwgVWv/rkDlSLgVt5nejSuVwS+u8bajPutyL4bkdU2f0DrxZG4zR0dSQyepre/VA4Z0DHbQpBMgtB6Lt4sKKMMRc9bIzyvvuZNyew874eAhmPJB2eD7hJg3sAsn1YaD75WUhiIVr75UZwYdB755JAgAk4OAcm5MCXCiwcY6b+HuMOg7p+36HAtWshlWWKp8juRt4EaiEja4/6/0L0gZvjpWLk4HInZRKZKeJg1wHn2Xn51ZBzlH8DuYorAxakITY3Ny7SAaDFjpoCkGETVPbTAMBlyXxw0+7zwDZOeiiqTkA50Y3Nwg9E7bUDXiCBZUxJtyykcQlSKnCgD5mLyZ0tWzvueKJeTOF7ORCPhY1oM7nNPFqOC2OlsI+nmT4MiHUTnuH+NAZP34LEzbrciAmUtjvehMiZC63t8/I/ElXWTY+wrgSBSBZo7xF6z/fUfwJs6JUew5dQYK8rUgL8zUJTRJ2eq2pg1uNxGzJ7i5+f+lDt4Lg/7HFrylRfnwgLShVH7lBy69nSFYzo+hdspKWi0LihLetubrVrwj1zWZmInb99ul9b0kxCU+IF12ByqygQZ7x/aFMYRQc6cxXz8CX3qhIxA2BjLw06uns/oJQL3Sta/M417hjEITn87oJiRr+++KQAteOIEjMZiAUkr5ftMnms4bkZmMYMm84w7CJ2XcnEoQMd7NE/brMjDeRmFh8W/xriPAQ72Ra7hV5gQuPIQobuT2t7bL4SpBAbuWvUzg==
    password: AgAL6dFMrPQ9syp1dPq/q+REzBpa1P3r81R+Z8IuK3fVoBcq6OCh/NVRkZ4U1WnY1Fi/FE6QqpVZ338/8+W+xRM7ZC60jHMi3vywgLlk+5agi1MnhOVb5eTUQFWDecPsPKLljDYq0IsKoCrUrr1WjvY8HrRcusD8f396yl/WUoMOueooEhLm+Ip2CP3XXHnNlJDJ6UXiE++hMOPAeXWgocw0zcpxSAGFxL8iNweQ50aTD0JsA0ZGGKgActaEYWFVNg5EyVfP9k4HokdkJt5WhSY+jtqFdFPOfW1O/oSjBxiABEltJEGbO/vRhoRUSHwXHY3lK5eQ1mck9YGAY5cYtowLU85K+QyQ+bCFo5yUEkkdRpWUJg/58tNaNXfth53Qnlo+yhnb9hjnoESlJ4+ng6kWY6rPARExTEd2RUgvZp+3IFmSmLQGuxV2Tk6yM0i1ShIhDFjH+lHgOqot2hDviQT9TZv3HWxPkaDfBSBOQ4HZl7Z3Lnk6Rl8jV85LOCev+rW4EoApb6NfJcYkkO8V7gQXJL+cOKJ1Oudttfx0B8VW9PTCdaElbHMxnt10lDkR+8QFXeYzfajVViUZ/c25jTcnPQ+2u5AmAQa/8bU3wnh8IBON8nscbkG+9XF5bNbykQdnDUZ91WUj6RHr3TaxEo4Scx7NQeTiPdC54YICyUgGiQ4m3HlFDSarBVIUjSzffb0gFoltHkk1yWR59K1KgGCm4gl0KZLWOQS69ydcQqUSfA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: rabbitmq-credentials
      namespace: email
    type: Opaque
