{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "fanzone-auth-bff.fullname" . }}-secrets
  labels:
    {{- include "fanzone-auth-bff.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef | default "gcp-secret-store" }}
    kind: ClusterSecretStore
  target:
    name: {{ include "fanzone-auth-bff.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: KEYCLOAK_CLIENT_SECRET
      remoteRef:
        key: {{ printf "%s-fanzone-keycloak-client-secret" .Values.gcp.secretManager.secretPrefix }}
    - secretKey: SESSION_SECRET
      remoteRef:
        key: {{ printf "%s-fanzone-bff-session-secret" .Values.gcp.secretManager.secretPrefix }}
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: {{ printf "%s-fanzone-redis-password" .Values.gcp.secretManager.secretPrefix }}
{{- end }}
