apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openfga
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: tesserix
    app.kubernetes.io/component: infrastructure
    environment: prod
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: marketplace
  source:
    repoURL: https://github.com/tesserix/tesserix-k8s.git
    targetRevision: HEAD
    path: k8s/apps/marketplace/openfga
  destination:
    server: https://kubernetes.default.svc
    namespace: marketplace
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
