{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "fanzone-prediction.fullname" . }}
  labels:
    {{- include "fanzone-prediction.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "fanzone-prediction.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Chart.Name }}
        minAllowed:
          memory: {{ .Values.vpa.minAllowed.memory | quote }}
        maxAllowed:
          memory: {{ .Values.vpa.maxAllowed.memory | quote }}
        controlledResources: ["memory"]
      {{- if .Values.vpa.excludeIstioProxy }}
      - containerName: istio-proxy
        mode: "Off"
      {{- end }}
{{- end }}
