apiVersion: v1
kind: Service
metadata:
  name: postsocial-redis
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: postsocial-redis
    app.kubernetes.io/part-of: postsocial
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      name: redis
  selector:
    app.kubernetes.io/name: postsocial-redis
