apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homechef-api.yaml
  - identity-bootstrap.yaml
  - homechef-auth-bff.yaml
  - homechef-db-seed.yaml
  - homechef-secrets.yaml
  - homechef-web.yaml
  - homechef-vendor-portal.yaml
  - homechef-admin-portal.yaml
  - homechef-delivery-portal.yaml
  - homechef-istio.yaml
  - homechef-postgres.yaml
